### PR TITLE
Miscellaneous improvements

### PR DESCRIPTION
**Pull request by udan11**
This pull request contains small, miscellaneous improvements to the controls found in user preferences.

### CODE REVIEW

**Comment by SamSaffron** [comment]
@lis2 can you review / approve?

**Comment by lis2** [comment]
I read the code and I think it is good that you want to make that action consistent. 

I also played with that to ensure it works as expected. I noticed only one small difference. In the original design we had `cancel` button:

image

And with a new approach, it is gone:

image

You just made the whole behaviour consistent but maybe it would be nice to have that `cancel` button.

Especially that if you type incorrect private key and click `Enable Encrypted Messages` it will just hang:
image

**Comment by udan11** [comment]
I reintroduced the <kbd>cancel</kbd> button and also made it show an error message if the key is wrong.

**Comment by lis2** [comment]
I played with that, works like a charm :)

**Review by lis2 — APPROVED** [review]

**Pull request merged**
